### ISSUE TITLE
Restrict code generation to pre-publish (not on install)

### ISSUE THREAD

**Issue by alexcasalboni** [aletheia/iam-policy-generator#19]
I think it'd be a better approach if the code generation step happened before publishing to NPM, rather than on post-install on the client.

This change will require some sort of sync mechanism with the original JSON file. And also an easy way on your side to automatically create a PR and publish a new version every time that JSON changes (if tests succeed).

**Comment by aletheia** [comment]
The current approach fetches policy.json on install and generates Typescript classes to do the magic, then compile them.

Shifting generator before publishing would not require Typescript in NPM package and allow everyone getting the same version of APIs.

On the other side, it requires some way to check whenever remote file is updated. Maybe we could use cloudwatch synthetics to monitor that.

Definitely an idea to work on for release 1.2

**Comment by asyschikov** [comment]
It should be bundled in the package so that it is immutable and versioned. Also so that the package and its policies.js can be audited before installation.

**Comment by aletheia** [comment]
> It should be bundled in the package so that it is immutable and versioned. Also so that the package and its policies.js can be audited before installation.

It is going to work exactly like that. Plus we're investigating an efficient and cost-effective way to monitor source policy.js for changes and open a PR to a new release.
