### ISSUE TITLE
iam-policy-generator's PolicyStatement' is not assignable to parameter of @aws-cdk's PolicyStatement

### ISSUE THREAD

**Issue by kopkunka55** [aletheia/iam-policy-generator#24]
I've tried to attach Amazon Rekognition access policies to Lambda following [the example](https://github.com/aletheia/iam-policy-generator/tree/master/examples/cdk-lambda-function)

```typescript
hanlder.addToRolePolicy(
    new PolicyStatementFactory()
    .setEffect(iam.Effect.ALLOW)
    .addAction(Action.REKOGNITION.DETECT_FACES)
    .build()
    );
```

but it says
```shell
Argument of type 'import("iam-policy-generator/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement' is not assignable to parameter of type 'import("/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement'.
```

**Environment**
Node.js: 12.16.1
iam-policy-generator: ^1.1.1
@aws-cdk/aws-iam: 1.31.0

**Comment by nihakue** [comment]
Having the same issue. Could it be a similar problem to https://github.com/aws/aws-cdk/issues/979 ? With Typecript's weird private property constraints?
