### ISSUE TITLE
Simplify hierarchy for CDK

### ISSUE THREAD

**Issue by alexcasalboni** [aletheia/iam-policy-generator#7]
I'd expect `PolicyStatementGenerator` and `PolicyGenerator` to be the same class, specialized for the CDK. There is always time to extract a CDK-agnostic library later on, if needed.

This way, the sample code will look easier and the source code will be much simpler to understand (for now).

**Comment by aletheia** [comment]
Since you import from package, you could simply ignore `PolicyFactory` (new name) in favour of `PolicyStatementFactory`, then rewrite the example as 

```javascript

import {PolicyStatementFactory} from 'iam-policy-generator'

// your code defining a resource (i.e. a lambda function)

lambda.addRolePolicy(new PolicyStatementFactory().build())

```

**Comment by aletheia** [comment]
Closing this issue by now.
