### ISSUE TITLE
Alternative syntax

### ISSUE THREAD

**Issue by alexcasalboni** [aletheia/iam-policy-generator#9]
I think this syntax would make the library easier to use and more flexible:

```typescript

new PolicyStatementGenerator()
  .service(Service.S3)
  .action(API.S3.PUT_OBJECT)
  .resources(["*"])
  .build()
```
 
and even:

```typescript

new PolicyStatementGenerator()
  .service(Service.S3)
  .actions(API.S3.PUT_OBJECT, API.S3.LIST_BUCKET)
  .allResources()
  .build()
```

Actually, I'm wondering why we need to specify the `service` in the first place, since we are already passing `API.S3.PUT_OBJECT` :) Couldn't the library infer the service starting from the action?

**Comment by aletheia** [comment]
`service` has been removed in #6

**Comment by lusentis** [comment]
The current syntax better respects latest CDK versions.
(personally, I liked more the method chaining approach of the old versions anyway).

There's no way to avoid calling the .build() method? It's easy to forget, and CDK's error is a bit cryptic.

**Comment by lusentis** [comment]
`PolicyStatementGenerator` could extend CDK's PolicyStatement :)

**Comment by aletheia** [comment]
Unfortunately `PolicyStatementFactory` (new name in upcoming 1.0) extends `PolicyFactory` and multiple inheritance is not supported. Moreover, currently the generator support only a subset of attributes of the parent class, thus making it expend `PolicyStatement` could be misleading.
